# Pull gems from RubyGems
source 'https://rubygems.org'

# Radix gems
gem 'compass'
gem 'sass'
gem 'scss-lint'
gem 'bootstrap-sass', '~> 3.2'
gem 'compass_radix', '~> 3.1.5'
#gem 'oily_png', '~> 1.1.1'
gem 'breakpoint'
gem 'toolkit', '~> 2.6'
gem 'sass-globbing', '~> 1.1.1'
#gem 'terminal-notifier'
gem 'compass-normalize', '~>1.4.3'

# Now that you're using Bundler, you need to run `bundle exec compass watch` instead of simply `compass watch`.
